# Generated by Django 5.2.1 on 2025-12-05 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('lower_limit', models.IntegerField(blank=True, null=True)),
                ('upper_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(default='answer')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('trigger_type', models.TextField(blank=True, max_length=64, null=True)),
                ('trigger_value', models.FloatField(blank=True, null=True)),
                ('trigger_comparator', models.TextField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, max_length=64, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('easy_tasks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('medium_tasks', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('hard_tasks', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('has_happened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.FloatField()),
                ('duration', models.PositiveIntegerField()),
                ('easy_tasks', models.PositiveIntegerField()),
                ('medium_tasks', models.PositiveIntegerField()),
                ('hard_tasks', models.PositiveIntegerField()),
                ('tasks_predecessor_p', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.FloatField(default=0.0, help_text='Experience level of the member (0.0+)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('motivation', models.FloatField(default=0.75, help_text='Motivation level of the member (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('familiar_tasks', models.IntegerField(default=0, help_text='Number of tasks the member is familiar with', validators=[django.core.validators.MinValueValidator(0)])),
                ('familiarity', models.FloatField(default=0.0, help_text='Ratio of familiar tasks to total tasks (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('stress', models.FloatField(default=0.1, help_text='Current stress level of the member (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['team', 'skill_type__name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_index', models.PositiveIntegerField()),
                ('multi', models.BooleanField()),
                ('explanation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('stress_weekend_reduction', models.FloatField(default=0.15, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('stress_overtime_increase', models.FloatField(default=0.05)),
                ('stress_error_increase', models.FloatField(default=0.02)),
                ('done_tasks_per_meeting', models.IntegerField(default=50)),
                ('train_skill_increase_rate', models.FloatField(default=0.1)),
                ('cost_member_team_event', models.FloatField(default=500.0)),
                ('randomness', models.TextField(default='full')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_counter', models.IntegerField(default=0)),
                ('step_counter', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('budget', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('poisson_sum', models.IntegerField(default=0)),
                ('poison_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_limit', models.PositiveIntegerField(default=100)),
                ('time_limit', models.PositiveIntegerField(default=100)),
                ('quality_limit', models.PositiveIntegerField(default=100)),
                ('budget_p', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('time_p', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('quality_k', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='SimulationEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.TextField(blank=True)),
                ('type', models.TextField(blank=True, max_length=16)),
                ('limit_type', models.TextField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationFragment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('last', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the skill type (e.g., 'Junior Developer')", max_length=32, unique=True)),
                ('cost_per_day', models.FloatField(default=100, help_text='Daily cost for this skill type', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('error_rate', models.FloatField(default=0.05, help_text='Probability of introducing errors (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('throughput', models.FloatField(default=1, help_text='Base productivity multiplier', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('management_quality', models.PositiveSmallIntegerField(default=0, help_text='Management skill quality (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('development_quality', models.PositiveSmallIntegerField(default=100, help_text='Development skill quality (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('signing_bonus', models.FloatField(default=0, help_text='One-time bonus paid when hiring', validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Skill Type',
                'verbose_name_plural': 'Skill Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveIntegerField()),
                ('done', models.BooleanField(default=False)),
                ('bug', models.BooleanField(default=False)),
                ('correct_specification', models.BooleanField(default=True)),
                ('unit_tested', models.BooleanField(default=False)),
                ('integration_tested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='team', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateScenario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='default_scenario_name')),
                ('story', models.TextField(blank=True, default='', max_length=65536)),
                ('studio_template_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_points', models.IntegerField(blank=True, default=0, null=True)),
                ('ended', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
