# Generated by Django 5.2.1 on 2025-12-05 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventeffect',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='app.event'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.questioncollection'),
        ),
        migrations.AddField(
            model_name='eventstatus',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_status', to='app.scenariostate'),
        ),
        migrations.AddField(
            model_name='simulationend',
            name='simulation_fragment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_end', to='app.simulationfragment'),
        ),
        migrations.AddField(
            model_name='action',
            name='simulation_fragment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.simulationfragment'),
        ),
        migrations.AddIndex(
            model_name='skilltype',
            index=models.Index(fields=['name'], name='app_skillty_name_039e54_idx'),
        ),
        migrations.AddField(
            model_name='member',
            name='skill_type',
            field=models.ForeignKey(blank=True, help_text='The skill type of this member', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.skilltype'),
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.task'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(help_text='The team this member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.team'),
        ),
        migrations.AddField(
            model_name='simulationfragment',
            name='template_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_fragments', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='template_scenario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_card', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='questioncollection',
            name='template_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_collections', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='managementgoal',
            name='template_scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_goal', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='event',
            name='template_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='course',
            name='scenarios',
            field=models.ManyToManyField(to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.scenarioconfig'),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='userscenario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='user_scenario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='app.userscenario'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.userscenario'),
        ),
        migrations.AddField(
            model_name='scenariostate',
            name='user_scenario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='app.userscenario'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['team'], name='app_member_team_id_12000f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['skill_type'], name='app_member_skill_t_9d92ab_idx'),
        ),
    ]
