# Generated by Django 5.2.1 on 2025-12-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.TextField(default='', max_length=32, null=True)),
                ('response_type', models.TextField(default='', max_length=32, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('component_counter', models.PositiveIntegerField(null=True)),
                ('step_counter', models.PositiveIntegerField(null=True)),
                ('day', models.PositiveIntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('tasks_todo', models.PositiveIntegerField(null=True)),
                ('tasks_done', models.PositiveIntegerField(null=True)),
                ('tasks_unit_tested', models.PositiveIntegerField(null=True)),
                ('tasks_integration_tested', models.PositiveIntegerField(null=True)),
                ('tasks_bug_discovered', models.PositiveIntegerField(null=True)),
                ('tasks_bug_undiscovered', models.PositiveIntegerField(null=True)),
                ('tasks_done_wrong_specification', models.PositiveIntegerField(null=True)),
                ('bugfix', models.BooleanField(blank=True, null=True)),
                ('unittest', models.BooleanField(blank=True, null=True)),
                ('integrationtest', models.BooleanField(blank=True, null=True)),
                ('meetings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('teamevent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overtime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('question_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.questioncollection')),
                ('user_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.userscenario')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryMemberChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('skill_type_name', models.TextField(max_length=64)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_changes', to='history.history')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.PositiveBigIntegerField()),
                ('motivation', models.FloatField()),
                ('stress', models.FloatField()),
                ('xp', models.FloatField()),
                ('skill_type_name', models.TextField(max_length=64)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='history.history')),
                ('skill_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.skilltype')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='history.history')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_selection', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='history.historyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('tasks_todo', models.PositiveIntegerField(default=0)),
                ('tasks_done', models.PositiveIntegerField(default=0)),
                ('tasks_unit_tested', models.PositiveIntegerField(default=0)),
                ('tasks_integration_tested', models.PositiveIntegerField(default=0)),
                ('tasks_bug_discovered', models.PositiveIntegerField(default=0)),
                ('tasks_bug_undiscovered', models.PositiveIntegerField(default=0)),
                ('tasks_done_wrong_specification', models.PositiveIntegerField(default=0)),
                ('tasks_accepted', models.PositiveIntegerField(default=0)),
                ('tasks_rejected', models.PositiveIntegerField(default=0)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('time_score', models.PositiveSmallIntegerField(default=0)),
                ('budget_score', models.PositiveSmallIntegerField(default=0)),
                ('question_score', models.PositiveSmallIntegerField(default=0)),
                ('template_scenario_id', models.PositiveIntegerField(blank=True, null=True)),
                ('template_scenario_name', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('avg_poisson_value', models.FloatField(blank=True, null=True)),
                ('time_played', models.PositiveIntegerField(blank=True, null=True)),
                ('randomness', models.TextField(blank=True, null=True)),
                ('user_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='app.userscenario')),
            ],
        ),
    ]
