name: softdsim
services:
  maria_application_db:
    image: mariadb:11.8-noble
    restart: unless-stopped
    env_file: ../backend/.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - maria_store:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  maria_store:
