from app.dto.request import Workpack


"""
Original set of user parameters used in the work packs from first development of softDsim
"""
USERPARAMETERS_OG = [
    Workpack(
        bugfix=False,
        unittest=False,
        integrationtest=False,
        meetings=20,
        training=5,
        teamevent=False,
        overtime=2,
    ),
    Workpack(
        bugfix=False,
        unittest=False,
        integrationtest=False,
        meetings=20,
        training=5,
        teamevent=False,
        overtime=0,
    ),
    Workpack(
        bugfix=False,
        unittest=False,
        integrationtest=False,
        meetings=0,
        training=0,
        teamevent=False,
        overtime=1,
    ),
    Workpack(
        bugfix=True,
        unittest=True,
        integrationtest=False,
        meetings=2,
        training=1,
        teamevent=False,
        overtime=1,
    ),
    Workpack(
        bugfix=True,
        unittest=True,
        integrationtest=True,
        meetings=2,
        training=1,
        teamevent=False,
        overtime=1,
    ),
    Workpack(
        bugfix=True,
        unittest=True,
        integrationtest=True,
        meetings=5,
        training=0,
        teamevent=True,
        salary=2,
        overtime=1,
    ),
    Workpack(
        bugfix=True,
        unittest=True,
        integrationtest=False,
        meetings=0,
        training=0,
        teamevent=True,
        overtime=2,
    ),
    Workpack(
        bugfix=True,
        unittest=True,
        integrationtest=False,
        meetings=15,
        training=5,
        teamevent=False,
        salary=2,
        overtime=1,
    ),
]
