# Generated by Django 5.2.1 on 2025-12-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='salary',
        ),
    ]
